name = "burns-legal-enhanced-authless"
main = "src/burns-legal-enhanced-full.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[vars]
SUPABASE_URL = "https://nqkzqcsqfvpquticvwmk.supabase.co"

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "BurnsLegalEnhancedMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BurnsLegalEnhancedMCP"]