name = "burns-legal-enhanced-authless"
main = "src/index.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[vars]
SUPABASE_URL = "https://nqkzqcsqfvpquticvwmk.supabase.co"

# Secret configured in Cloudflare dashboard
# SUPABASE_SERVICE_ROLE_KEY

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "BurnsLegalMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BurnsLegalMCP"]