name = "burns-legal-enhanced-authless"
main = "src/burns-legal-enhanced.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[vars]
SUPABASE_URL = "https://nqkzqcsqfvpquticvwmk.supabase.co"

# Secret configured in Cloudflare dashboard
# SUPABASE_SERVICE_ROLE_KEY

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "BurnsLegalEnhancedMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BurnsLegalEnhancedMCP"]

[[migrations]]
tag = "v2"
renamed_classes = [
  { from = "BurnsLegalMCP", to = "BurnsLegalEnhancedMCP" },
  { from = "BurnsLegalEnhancedComplete", to = "BurnsLegalEnhancedMCP" }
]