name = "burns-legal-enhanced-authless"
main = "src/index.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[vars]
SUPABASE_URL = "https://nqkzqcsqfvpquticvwmk.supabase.co"
MCP_SERVER_NAME = "burns-legal-mcp"

# Secret to be added in Cloudflare Dashboard > Worker > Settings > Variables > Encrypt:
# SUPABASE_SERVICE_ROLE_KEY = [add as encrypted secret in dashboard]

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "MyMCP"

[[migrations]]
tag = "v4"
new_classes = ["MyMCP"]
