name = "burns-legal-mcp-202508182039"
main = "mcp-wrapper.js"
compatibility_date = "2024-11-02"
node_compat = true

[vars]
SUPABASE_URL = "https://nqkzqcsqfvpquticvwmk.supabase.co"
SUPABASE_FUNCTION_URL = "https://nqkzqcsqfvpquticvwmk.functions.supabase.co"
EDGE_FUNCTION_PATH = "/advanced-semantic-search"
ENABLE_DEBUG_HEADERS = "false"
CORS_ALLOWED_ORIGINS = "*"

[env.production]


