name = "burns-legal-enhanced-authless"
main = "src/index.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[vars]
SUPABASE_URL = "https://nqkzqcsqfvpquticvwmk.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xa3pxY3NxZnZwcXV0aWN2d21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA3NDI0OTMsImV4cCI6MjA0NjMxODQ5M30.LQklkf3vX-dkkrN8gEcwHsQl7KKFYV_tifhEJtJrUX8"
MCP_SERVER_NAME = "burns-legal-mcp"

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "MyMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyMCP"]

[[migrations]]
tag = "v2"
renamed_classes = [
  { from = "BurnsLegalEnhancedComplete", to = "MyMCP" }
]

[[migrations]]
tag = "v3"
renamed_classes = [
  { from = "BurnsLegalEnhancedMCP", to = "MyMCP" },
  { from = "BurnsLegalMCP", to = "MyMCP" }
]
