name: Deploy MCP and Search Workers

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN || secrets.CF_API_TOKEN || secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Wrangler
        run: npm i -g wrangler@3

      - name: Seed production secret(s)
        run: |
          echo -n "$SUPABASE_SERVICE_ROLE_KEY" | wrangler secret put SUPABASE_SERVICE_ROLE_KEY --env production -c wrangler-mcp.toml
          echo -n "$SUPABASE_SERVICE_ROLE_KEY" | wrangler secret put SUPABASE_SERVICE_ROLE_KEY --env production -c wrangler-search.toml

      - name: Deploy MCP worker
        run: wrangler deploy --env production -c wrangler-mcp.toml --minify

      - name: Deploy Search worker
        run: wrangler deploy --env production -c wrangler-search.toml --minify

      - name: Smoke test MCP worker
        run: |
          set -e
          curl -sS https://burns-legal-mcp-202508182039.rburns-fresno.workers.dev/healthz || true

      - name: Smoke test Search worker
        run: |
          set -e
          curl -sS https://burns-legal-enhanced-authless.rburns-fresno.workers.dev/healthz || true