name: Deploy Workers

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy MCP worker (token+account)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '3.80.5'
          command: secret put SUPABASE_SERVICE_ROLE_KEY -c wrangler-mcp.toml <<<"${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"

      - name: Deploy MCP worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '3.80.5'
          command: deploy -c wrangler-mcp.toml

      - name: Deploy Search worker (token+account)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '3.80.5'
          command: secret put SUPABASE_SERVICE_ROLE_KEY -c wrangler-search.toml <<<"${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"

      - name: Deploy Search worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '3.80.5'
          command: deploy -c wrangler-search.toml

      - name: Smoke test MCP /healthz
        run: |
          curl -sS https://burns-legal-mcp-202508182039.rburns-fresno.workers.dev/healthz || true

      - name: Smoke test Search /healthz
        run: |
          curl -sS https://burns-legal-enhanced-authless.rburns-fresno.workers.dev/healthz || true