name: Deploy Burns Legal Enhanced MCP

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build TypeScript
        run: npm run build
        
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          config: wrangler.enhanced.toml
          secrets: |
            SUPABASE_SERVICE_ROLE_KEY
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          
      - name: Create deployment record
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              environment: '${{ inputs.environment || 'production' }}',
              production_environment: '${{ inputs.environment == 'production' }}',
              description: 'Burns Legal Enhanced MCP v1.0',
              required_contexts: [],
              auto_merge: false
            });
            
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: 'success',
              environment_url: 'https://burns-legal-enhanced-authless.rburns-fresno.workers.dev',
              description: 'Deployment successful'
            });
            
      - name: Test deployment
        run: |
          sleep 10
          curl -f https://burns-legal-enhanced-authless.rburns-fresno.workers.dev/health || exit 1
          
      - name: Tag stable release
        if: github.ref == 'refs/heads/main' && success()
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          git tag -a "deploy-$TIMESTAMP" -m "Automated deployment at $TIMESTAMP"
          git push origin "deploy-$TIMESTAMP"